name: using secret keys as part of workflow

on: push

jobs:
  run-on: ubuntu-latest
  steps:
    env:
      SOME_JOB_ENVIRONMENT_VARIABLE: "SOME alphanumeric"
    -name: Log into aws
    uses: aws-actions/configure-aws-credentials@v2
    with:
      aws-access-key-id: ${{secrets.AWS_ACCES_KEY_ID}}
      aws-secret-access-key: ${{secrets.AWS_SECRET_ACCES_KEY}}
      aws-region: us-east-2
    
